from itertools import chain


def all_markers():
    return set(chain.from_iterable(REGIONS.values()))


REGIONS: dict[str, tuple[str, ...]] = {
    "Acrithia": (
        "Astero's Spear",
        "Camp Omicron",
        "Duelling Kegs",
        "Fated Heel",
        "Final March",
        "Heir Apparent",
        "Legion Ranch",
        "Nereid Keep",
        "Patridia",
        "Riverlands",
        "Swordfort",
        "The Brinehold",
        "Thetus Ring",
        "Weary Slumber",
    ),
    "Allods Bight": (
        "A Captain's Repose",
        "Allod's Children",
        "Belaying Trace",
        "Blunder Bight",
        "Breath of Cetus",
        "Gangrenous Hollow",
        "Harpy's Perch",
        "Homesick",
        "Mercy's Wail",
        "Rumhold",
        "Scurvyshire",
        "The List",
        "The Rumroad",
        "The Stone Plank",
        "The Turncoat",
        "Titan's End",
        "Witch's Last Flight",
    ),
    "Ash Fields": (
        "Ashtown",
        "Camp Omega",
        "Cometa",
        "Electi",
        "Gunslinger's Pass",
        "Mount Blackmoth",
        "Mount Brimstone",
        "Omega Valley",
        "Sootflow",
        "Tar Creek",
        "The Ashfort",
        "The Calamity",
        "The Red River",
        "The Stillness",
        "Twin Flames",
        "Wasteful Calm",
    ),
    "Basin Sionnach": (
        "Basin Sionnach",
        "Basinhome",
        "Cunning Cross",
        "Cuttail Station",
        "Lamplight",
        "Radiant Shore",
        "Sess",
        "Stoic",
        "The Den",
        "The Foxfields",
        "Torchwood",
    ),
    "Callahans Passage": (
        "Callahan's Eye",
        "Chapel Access",
        "Cragsfield",
        "Cragsroad",
        "Cragstown",
        "Crumbling Post",
        "Lingering Lashes",
        "Lochan",
        "Lochan Berth",
        "Lost Tops",
        "Overlook Hill",
        "Scáth Passing",
        "Sioc Approach",
        "Solas Gateway",
        "Solas Gorge",
        "Soured Fields",
        "The Crumbling Passage",
        "The Key",
        "The Lance",
        "The Latch",
        "The Procession",
        "The Rust Road",
        "The Stern",
        "Twisted Mumble",
        "Whispering Gulch",
        "White Chapel",
        "Winding Crag",
    ),
    "Callums Cape": (
        "Callum's Keep",
        "Camp Hollow",
        "Holdout",
        "Hollowhill",
        "Ire",
        "Lookout",
        "Naofa",
        "Princefal Burn",
        "Scouts Jest",
        "The Dreg",
        "The Gunwall",
        "The River Vein",
        "Trail of the Dead",
        "Valta Downs",
        "Vex",
    ),
    "The Clahstra": (
        "Bewailing Fort",
        "East Narthex",
        "Penitent Inlet",
        "Saint's Crossing",
        "Second Prayer",
        "Sleeping Choir",
        "Sly Passage",
        "The Four Pillars",
        "The Garth",
        "The Laity",
        "The Treasury",
        "The Vault",
        "Third Chapter",
        "Transept",
        "Watchful Nave",
        "Weephome",
        "Woodlouse Ledge",
    ),
    "Clanshead Valley": (
        "Bramble Field",
        "Fallen Crown",
        "Fort Ealar",
        "Fort Esterwild",
        "Fort Windham",
        "Lost Orphans",
        "Sweetholt",
        "Tallowild",
        "The Bastard's Channel",
        "The King",
        "The Pike",
        "The Weathered Advance",
        "Throne of Druiminn",
    ),
    "Deadlands": (
        "Abandoned Ward",
        "Biting Tarn",
        "Border Concourse",
        "Border Thicket",
        "Brine Glen",
        "Callahan's Belt",
        "Callahan's Boot",
        "Callahan's Gate",
        "Carpal Trail",
        "Cemetary Junction",
        "Cemetary Lane",
        "Coracoid Footpath",
        "Crumbling Passage",
        "Hope's Causeway",
        "Iron's End",
        "Jaspar Range",
        "Liberation Point",
        "Mandible Crossroads",
        "Marrow Copse",
        "Mercy Meadow",
        "Mercy's End",
        "Overgrown Pasture",
        "Path to the Sun",
        "Pommel Annex",
        "Sun's Hollow",
        "Sunhaven Gateway",
        "Tarsal Pathway",
        "The Abbey Drag",
        "The Blade",
        "The Boneyard",
        "The Crossing",
        "The Great March",
        "The Iron Passage",
        "The Iron Road",
        "The Pits",
        "The Plaza",
        "The Salt Farms",
        "The Salt March",
        "The Salt Trail",
        "The Shorn Fields",
        "The Spine",
        "The Steppes",
    ),
    "The Drowned Vale": (
        "Bootnap",
        "Coaldrifter Stead",
        "Eastmarch",
        "Esterfal",
        "Fleetsfall River",
        "Linger",
        "Loggerhead",
        "Singing Serpents",
        "Sop Fields",
        "Splinter Pens",
        "Sprite's Game",
        "The Baths",
        "The Other Vein",
        "The Saltcaps",
        "The Turtlerocks",
        "The Wash",
        "The Willow Wood",
        "Vessel",
        "Wisp's Warning",
    ),
    "Endless Shore": (
        "Balor's Crown",
        "Battered Landing",
        "Brackish Point",
        "Dannan Coast",
        "Dearg's Fang",
        "Enduring Wake",
        "Iron Junction",
        "Kelpie's Mane",
        "Kelpie's Tail",
        "Liegehearth",
        "Merrow's Rest",
        "Saltbrook Channel",
        "Sídhe Fall",
        "The Dark Road",
        "The Evil Eye",
        "The North Star",
        "The Old Jack Tar",
        "The Overland",
        "The Selkie Bluffs",
        "The Styx",
        "The Whispering Waves",
        "Tuatha Watchpost",
        "Wellchurch",
        "Woodbind",
    ),
    "Farranac Coast": (
        "Apollo's Landing",
        "Cackling Strand",
        "Carrion Fields",
        "Cora Lushlands",
        "Cormac Beach",
        "Gulf of the Daughters",
        "Hermes Inlet",
        "Huskhollow",
        "Iuxta Gulf",
        "Kardia",
        "Liberation Street",
        "Macha's Keening",
        "Mara",
        "McCarthy Fields",
        "Mooring Dens",
        "Pleading Wharf",
        "Scarp of Ambrose",
        "Scythe",
        "Sickle Hill",
        "Skeleton Road",
        "Sunder Beach",
        "Terra",
        "The Bay of Artemis",
        "The Bone Haft",
        "The Heart Road",
        "The Jade Cove",
        "The Mirror",
        "The Reaping Fields",
        "The River Mercy",
        "The Snag",
        "Transient Valley",
        "Victa",
    ),
    "Fisherman's Row": (
        "Arcadia",
        "Bident Crossroads",
        "Black Well",
        "Dankana Post",
        "Eidolo",
        "Fort Ember",
        "Hangman's Court",
        "Heart of Rites",
        "House Roloi",
        "Lake Nerites",
        "Liberty Hill",
        "Oceanwatch",
        "Peripti Landing",
        "Progonos Watch",
        "The Rite Road",
        "The Satyr Stone",
        "Torch of Demeter",
    ),
    "Godcrofts": (
        "Argosa",
        "Barreller's Way",
        "Den of Thieves",
        "Exile",
        "Fleecewatch",
        "Isawa",
        "Lipsia",
        "Peripti Depths",
        "Perpetua Channel",
        "Pig Island",
        "Primus Trames",
        "Protos",
        "Saegio",
        "The Axehead",
        "Ursa Base",
        "Vicit Bay",
    ),
    "Great March": (
        "Camp Senti",
        "Dalton Meadow",
        "Dendró Field",
        "Eristown",
        "Fateless Grove",
        "Fengari",
        "Halting Valley",
        "Jack Field",
        "Jackboot Creek",
        "Legacy Pasture",
        "Leto",
        "Lionsfort",
        "Milowood",
        "Mors Range",
        "Myrmidon's Stay",
        "Remnant Acreage",
        "Remnant Villa",
        "Schala Estate",
        "Scrabbling Motte",
        "Serpent Charm",
        "Sitaria",
        "The Black Wing",
        "The Great March",
        "The Midmarch",
        "The River Senti",
        "The Spice Road",
        "The Swan",
        "The White Wing",
        "Violet Fields",
        "Violethome",
        "Zealous Approach",
    ),
    "The Heartlands": (
        "18th Sideroad",
        "Barronshire ",
        "Barronswall",
        "Barrony Ranch",
        "Barrony Road",
        "Cageroad",
        "Crater Basin",
        "Deeplaw Post",
        "Erimos Ranch",
        "Fort Providence",
        "Greenfield Orchard",
        "Harvester's Range",
        "Janus Field",
        "Kos Meadows",
        "Loftmire",
        "Lower Barrony Field",
        "Oleander Fields",
        "Oleander Homestead",
        "Pandora Compound",
        "Proexí",
        "Providence Field",
        "The Blemish",
        "The Breach",
        "The Fuming Pen",
        "The Orchard Wall",
        "The Plough",
        "The Rollcage",
        "The Salt Crossing",
        "Upper Barrony Field",
        "Upper Heartlands",
    ),
    "Howl County": (
        "Austriaca Reservoir",
        "Checkpoint Titim",
        "Fort Red",
        "Fort Rider",
        "Great Warden Dam",
        "Hungry Wolf",
        "Little Lamb",
        "Sickleshire",
        "Slipgate Outpost",
        "Snakewall",
        "Teller Farm",
        "The Hunting Grounds",
        "Viperwalk",
    ),
    "Kalokai": (
        "Baccae Ridge",
        "Bleary",
        "Camp Tau",
        "Clarity Meadow",
        "Hallow",
        "Ichorus Amphitheatre",
        "Lost Greensward",
        "Night's Regret",
        "Sourtooth",
        "South March",
        "Sweethearth",
        "The Stumble",
        "The Vineroad",
        "Vinum Rillet",
    ),
    "King's Cage": (
        "Blackguard's Wood",
        "Bloodcroft",
        "Celes Thicket",
        "Concubine",
        "Den of Knaves",
        "Eastknife",
        "Gibbet Fields",
        "Jester's Foil",
        "Leafless Whim",
        "Ocelot Bridge",
        "Scarlethold",
        "Slipchain",
        "Southblade",
        "The Bailie",
        "The Manacle",
        "The River Blaise",
        "Wolfsbait",
    ),
    "The Linn of Mercy": (
        "Blackroad",
        "Fort Duncan",
        "Gallant Gough Boulevard",
        "Hardline",
        "Lathair",
        "Merciful Strait",
        "Mudhole",
        "Nathair",
        "Outwich Ranch",
        "Rotdust",
        "Solas Burn",
        "The Crimson Gardens",
        "The Drone",
        "The First Coin",
        "The Great Scale",
        "The Last Grove",
        "The Long Whine",
        "The Prairie Bazaar",
        "The River Mercy",
        "Ulster Falls",
    ),
    "Loch Mór": (
        "Bastard's Blade",
        "Chattering Prairie",
        "Escape",
        "Fallen Fields",
        "Feirmor",
        "Lake Severspring",
        "Loch Mor",
        "Market Road",
        "Mercy's Wish",
        "Missing Bones",
        "Moon's Copse",
        "Ousterdown",
        "Pockfields",
        "Rip",
        "Tear",
        "The Founding Fields",
        "The Glean",
        "The Reaping Road",
        "The Roilfort",
        "Tomb of the First",
        "Westmarch",
        "Widow's Wail",
    ),
    "Marban Hollow": (
        "Bleating Plateau",
        "Bubble Basin",
        "Checkpoint Bua",
        "Deepfleet Valley",
        "Gaping Maw",
        "Lockheed",
        "Lockheed Breakers",
        "Lughbone Dam",
        "Maiden's Veil",
        "Mount Mac Tire",
        "Mox",
        "Oster Wall",
        "Pilgrimage",
        "Sanctum",
        "Slender Cove",
        "The Claim",
        "The Clutch",
        "The Curse",
        "The Spitrocks",
    ),
    "The Moors": (
        "Borderlane",
        "Gravekeeper's Holdfast",
        "Headstone",
        "Luch's Workshop",
        "Lyon's Wood",
        "MacConmara Barrows",
        "Moon's Walk",
        "Morrighan's Grave",
        "Ogmaran",
        "Reaching River",
        "Riverhill",
        "Scáth Copse",
        "The Cut",
        "The Graveyard",
        "The Mound",
        "The Spade",
        "The Wind Hills",
        "Wiccwalk",
        "Wiccwood",
    ),
    "Morgens Crossing": (
        "Allsight",
        "Bastard's Block",
        "Callum's Descent",
        "Crimson Thread",
        "Eversus",
        "Lividus",
        "Quietus",
        "Rising Calm",
        "The Bastard Sea",
        "Ultimus",
        "Velian Storm",
        "Warmonger Bay",
    ),
    "Nevish Line": (
        "Blackburn Canal",
        "Blackcoat Way",
        "Blinding Stones",
        "Graven Falls",
        "Grief Mother",
        "Mistle Shrine",
        "Nevish Trail",
        "Plumage",
        "Princefal",
        "Princefal Burn",
        "Tear Road",
        "The Aging Ocean",
        "The Arrow",
        "The Scrying Belt",
        "Tomb Father",
        "Unruly",
    ),
    "Oarbreaker Isles": (
        "Barrenson",
        "Bronze",
        "Castor",
        "Cat Step",
        "Fort Fogwood",
        "Gold",
        "Grisly Refuge",
        "Integrum",
        "Kofteri Channel",
        "Lion's Head Pass",
        "Obitum",
        "Partisan Island",
        "Pollux",
        "Posterus",
        "Reliqua Lagoon",
        "Sandalwood Beach",
        "Silver",
        "Skull Beach",
        "The Conclave",
        "The Dirk",
    ),
    "Origin": (
        "Arise",
        "Cado",
        "Dormio",
        "Exorior",
        "Finis",
        "Initium",
        "Noventus Passage",
        "Teichotima",
        "Temple Field",
        "The Dreamer's Road",
        "The Echo",
        "The Steel Road",
        "The Sundering",
        "World Star",
    ),
    "Reaching Trail": (
        "Brodytown",
        "Camp Eos",
        "Caragtais",
        "Duffy's Farm",
        "Dugan's Approach",
        "Dwyersfield",
        "Dwyerstown",
        "Elksford",
        "Featherfield",
        "Fisherman's Floe",
        "Fort Mac Conaill",
        "Harpy",
        "Hookhall",
        "Humidus",
        "Ice Ranch",
        "Limestone Holdfast",
        "Mac Conaill's Pass",
        "Mousetrap",
        "Nightchurch",
        "Pitfall",
        "Puncta",
        "Reprieve",
        "Scorpion",
        "The Ark",
        "The Bait",
        "The Cairns",
        "The Chicken Coop",
        "The Deckard",
        "The Knot",
        "The Reaching Heights",
        "The Rime Ledge",
        "The Rousing Fields",
        "The Scar",
        "The Squeeze",
        "Thýlak",
        "Windy Way",
    ),
    "Reavers Pass": (
        "Billhook Reach",
        "Binnacle Pitch",
        "Blackjack Junction",
        "Blissfin Beach",
        "Breakwater",
        "Cape Balderstone",
        "Clay Coffer",
        "Fort Rictus",
        "Jeweller's Bay",
        "Keelhaul",
        "Mount Haulwind",
        "Privateer's Bounty",
        "Scuttletown",
        "Sharkfin River",
        "The Bilge",
        "The Foreward Fathom",
        "The Furl",
        "The Whaler",
        "Thimble Base",
    ),
    "Red River": (
        "Camp Upsilon",
        "Cannonsmoke",
        "Climb",
        "Fort Matchwood",
        "Fragment Knolls",
        "Gunpowder Lane",
        "Judicium",
        "Minos",
        "Penance",
        "Perish",
        "Red Crossing",
        "The Red River",
        "Twelve Drops",
        "Victoria Hill",
    ),
    "Sableport": (
        "Aeyrie Bay",
        "Barronhome",
        "Cinderwick",
        "Creeping Drought",
        "Groggy Pinion",
        "Light's End",
        "Lord's Cellar",
        "Lye Fields",
        "Riven Downs",
        "Simmerset",
        "Slumbering Meadow",
        "Suture Lowlands",
        "Talonsfort",
        "The Pendant",
        "The Robin's Nest",
        "The Whetstone",
        "Waspwood",
        "Wormskive",
    ),
    "Shackled Chasm": (
        "A Careless Net",
        "A New Spring",
        "Autumn Pyres",
        "Final Step",
        "Firstmarch",
        "Gorgon Grove",
        "Hades Ladder",
        "Legion's Dawn",
        "Limewood Holdfast",
        "Manky Hills",
        "Reflection",
        "Savages",
        "Silk Farms",
        "Simo's Run",
        "Southreach",
        "The Bell Toll",
        "The Blue",
        "The First Rung",
        "The Foolish Maidens",
        "The Grave of Erastos",
        "The Plunging",
        "The Vanguard",
        "Widow's Web",
    ),
    "Speaking Woods": (
        "Calmland",
        "Cursed Court",
        "Fort Blather",
        "Hush",
        "Inari Base",
        "Mount Rell",
        "Mute",
        "Reaching River",
        "Rell Foothills",
        "Sotto Bank",
        "Stem",
        "The Filament",
        "Tine",
        "Wound",
    ),
    "Stema Landing": (
        "Acies Overlook",
        "Alchimio Estate",
        "Base Ferveret",
        "Base Sagitta",
        "Burnish Beach",
        "Desolation Beach",
        "Foreland",
        "Isle of Eros",
        "Stema Approach",
        "The Coil",
        "The Flair",
        "The North Wind",
        "The Spearhead",
        "The Wane",
        "The Wending Tether",
        "The West Line",
        "Ustio",
        "Verge Wing",
    ),
    "Stlican Shelf": (
        "Briar",
        "Broken Zephyr",
        "Calving",
        "Cavilltown",
        "Crystalfleet Inlet",
        "Desiccated Front",
        "Diarmaid's Plan",
        "Fort Hoarfrost",
        "Glassy Flats",
        "Port of Rime",
        "Revenant's Walk",
        "Searing Blind",
        "The Old Mourn",
        "The South Wind",
        "Thornhold",
        "Vulpine Watch",
    ),
    "Stonecradle": (
        "Buckler Sound",
        "Daihbi Point",
        "Fading Lights",
        "Longing",
        "The Cord",
        "The Dais",
        "The Heir's Knife",
        "The Loneliest Shore",
        "The Long Fast",
        "The Pram",
        "The Reach",
        "The Roiling Comets",
        "The Whorl",
        "Trammel Pool",
        "World's End",
    ),
    "Tempest Island": (
        "Anchor",
        "Blackwatch",
        "Cirris Valve",
        "Eros Lagoon",
        "Isle of Psyche",
        "Liar's Haven",
        "Liar's League",
        "Lost Airchal",
        "Pale Cnap",
        "Plana Fada",
        "Reef",
        "Sclera",
        "Skodio Isle",
        "Stratos Valve",
        "Surge Field",
        "Surge Gate",
        "Sweetworm",
        "The Gale",
        "The Iris",
        "The Outwood",
        "The Rush",
    ),
    "Terminus": (
        "Aspisa",
        "Bay of the Ward",
        "Bloody Palm Fort",
        "Cerberus Wake",
        "Dogbone",
        "Martyr's Fang",
        "Rising Loom",
        "Sever",
        "The Legion's Bounty",
        "The Phalanx",
        "The Respite",
        "Therizó",
        "Three Siblings",
        "Thunder Plains",
        "Thunderbolt",
        "Warlord's Stead",
        "Winding Bolas",
    ),
    "The Fingers": (
        "Captain's Dread",
        "Cavitatis",
        "Fort Barley",
        "Grapeshot Islands",
        "Headsman's Villa",
        "Mount Talio",
        "Plankhouse",
        "Rusty Anchor",
        "Second Man",
        "Tears of Tethys",
        "Tethys Base",
        "The Old Captain",
        "The Tusk",
        "The Wary Nymphae",
        "Titancall",
    ),
    "Umbral Wildwood": (
        "Adze Crossroads",
        "Amethyst",
        "Atropos' Fate",
        "Clotho's Refuge",
        "Dredgefield",
        "Golden Concourse",
        "GoldenRoot Ranch",
        "Hermit's Rest",
        "Lachesis' Tally ",
        "Leatherback Pathway",
        "Sentry",
        "Steely Fields",
        "Stray",
        "Terrapin Woods",
        "The Dredgewood",
        "The Foundry",
        "The Frontier",
        "The Gap",
        "The Strands",
        "Thunder Row",
        "Thunderfoot",
        "Vagrant Bastion",
        "Wasting Holt",
        "Weaver's Trail",
    ),
    "Viper Pit": (
        "Afric's Approach",
        "Austriaca River",
        "Blackthroat",
        "Deadsteps",
        "Earl Crowley",
        "Earl's Welcome",
        "Fleck Crossing",
        "Fort Viper",
        "Hardcaps",
        "Kirknell",
        "Lake Mioira",
        "Moltworth",
        "Path of the Charmed",
        "Serenity's Blight",
        "Snakehead Lake",
        "The Bloody Bowery",
        "The Friars",
        "The Lady's Lake",
        "The Rockaway",
        "The Slithering Scales",
        "The Tongue",
        "Twin Fangs",
    ),
    "Weathered Expanse": (
        "Bannerwatch",
        "Barrowsfield",
        "Crow's Nest",
        "Dullahan's Crest",
        "Eapoe",
        "Foxcatcher",
        "Frostmarch",
        "Huntsfort",
        "Kirkyard",
        "Necropolis",
        "Revenant's Path",
        "Rime Wastes",
        "Shattered Advance",
        "Spirit Watch",
        "The Ivory Bank",
        "The Ivory Sea",
        "The Spear",
        "The Stand",
        "The Weathered Wall",
        "The Weathering Halls",
        "Wightwalk",
        "Wraith's Gate",
    ),
    "Westgate": (
        "Ash Step",
        "Candle Hills",
        "Cattle March",
        "Ceo Highlands",
        "Cinder Road",
        "Coasthill",
        "Coastway",
        "Cobber's Lane",
        "Ember Hills",
        "Fand's Chain",
        "Fields of Badb",
        "Flidais' Pasture",
        "Handsome Hideaway",
        "Hillcrest",
        "Holdfast",
        "Inkwell Lane",
        "Kardia Road",
        "Killian Quarter",
        "Kingstone",
        "Longstone",
        "Lord's Mouth",
        "Lost Partition",
        "Rancher's Fast",
        "Reaver's Cove",
        "Sanctified Path",
        "Síochána Valley",
        "Taswell Point",
        "The Aging Ocean",
        "The Bulwark",
        "The Divide",
        "The Gallows",
        "The Hem",
        "The King's Road",
        "The Knight's Edge",
        "Triton's Curse",
        "Warden Walk",
        "Western Heartlands",
        "Westgate Keep",
        "Wire Road",
        "Wyattwick",
        "Zeus' Demise",
    ),
}
