from enum import Enum


class Service(Enum):
    BCONS = 'Bcons'
    PCONS_PIPES = 'Pcons & Pipes'
    SCONS = 'Scons'
    OIL = 'Oil'
    PETROL = 'Petrol'
    HEAVY_OIL = 'Heavy Oil'
    ENRICHED_OIL = 'Enriched Oil'
    CAMS = 'Cams'
    PAMS = 'Pams'
    SAMS = 'Sams'
    HAMS = 'Hams'
    NAMS = 'Nams'
    CONCRETE = 'Concrete'
    METAL_BEAMS = 'Metal Beams'
    BARBED_WIRE = 'Barbed Wire'
    SANDBAGS = 'Sandbags'
    FLAME_BARREL = 'Flame Barrel'
    ROCKET = 'Rocket'
    FLAME_ROCKET = 'Incendiary Rocket'
    MM_300 = '300mm'
    MM_250 = '250mm'
    MM_150 = '150mm'
    MM_120 = '120mm'
    MM_94_5 = '94.5mm'
    MM_75 = '75mm'


class VehicleService(Enum):
    MODIFICATION_CENTER = 'Modification Center'
    LIGHT_ASSEMBLY = 'Light Assembly'
    LIGHT_ASSEMBLY_MP = 'Light Assembly (Motor Pool)'
    LIGHT_ASSEMBLY_RF = 'Light Assembly (Rocket Factory)'
    LIGHT_ASSEMBLY_FS = 'Light Assembly (Field Station)'
    LIGHT_ASSEMBLY_TF = 'Light Assembly (Tank Factory)'
    LIGHT_ASSEMBLY_WP = 'Light Assembly (Weapons Platform)'
    LARGE_ASSEMBLY = 'Large Assembly'
    LARGE_ASSEMBLY_T = 'Large Assembly (Train)'
    LARGE_ASSEMBLY_HT = 'Large Assembly (Heavy Tank)'


class Region(Enum):
    KALOKAI = 'Kalokai'
    RED_RIVER = 'Red River'
    ACRITHIA = 'Acrithia'
    ASH_FIELDS = 'Ash Fields'
    TERMINUS = 'Terminus'
    ORIGIN = 'Origin'
    THE_FINGERS = 'The Fingers'
    GREAT_MARCH = 'Great March'
    THE_HEARTLANDS = 'The Heartlands'
    SHACKLED_CHASM = 'Shackled Chasm'
    WESTGATE = 'Westgate'
    ALLODS_BIGHT = 'Allods Bight'
    FISHERMANS_ROW = 'Fishermans Row'
    TEMPEST_ISLAND = 'Tempest Island'
    UMBRAL_WILDWOOD = 'Umbral Wildwood'
    LOCH_MOR = 'Loch Mór'
    THE_DROWNED_VALE = 'The Drowned Vale'
    FARRANAC_COAST = 'Farranac Coast'
    ENDLESS_SHORE = 'Endless Shore'
    THE_OARBREAKER_ISLES = 'The Oarbreaker Isles'
    GODCROFTS = 'Godcrofts'
    DEADLANDS = 'DeadLands'
    THE_LINN_OF_MERCY = 'The Linn of Mercy'
    MARBAN_HOLLOW = 'Marban Hollow'
    STONECRADLE = 'Stonecradle'
    WEATHERED_EXPANSE = 'Weathered Expanse'
    NEVISH_LINE = 'Nevish Line'
    MORGENS_CROSSING = 'Morgens Crossing'
    CALLAHANS_PASSAGE = 'Callahans Passage'
    THE_MOORS = 'The Moors'
    VIPER_PIT = 'Viper Pit'
    CALLUMS_CAPE = 'Callums Cape'
    CLANSHEAD_VALLEY = 'Clanshead Valley'
    REACHING_TRAIL = 'Reaching Trail'
    SPEAKING_WOODS = 'Speaking Woods'
    HOWL_COUNTY = 'Howl County'
    BASIN_SIONNACH = 'Basin Sionnach'
